sudo: required

dist: bionic


language: c


install:
  - sudo apt-get update -y
  - sudo apt-get install -y cmake tree python3 python3-dev python3-pytest python3-pip python3-setuptools python3-wheel python3-pytest


script:
  - cmake .
  - make
  - make test
  - python3 setup.py bdist_wheel
  - pip3 install -y dist/pylibgeohash*
  - pytest



